# Generated by Django 6.0 on 2025-12-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='about/')),
                ('bio_text', models.TextField()),
                ('cv_file', models.FileField(upload_to='cv/')),
                ('years_experience', models.IntegerField(default=0)),
                ('location', models.CharField(default='Bakı, Azərbaycan', max_length=100)),
            ],
            options={
                'verbose_name': 'Haqqımda',
                'verbose_name_plural': 'Haqqımda',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Əlaqə Mesajı',
                'verbose_name_plural': 'Əlaqə Mesajları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('instagram', 'Instagram'), ('medium', 'Medium')], max_length=20)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(help_text='FontAwesome class adı', max_length=50)),
            ],
            options={
                'verbose_name': 'Sosial Media',
                'verbose_name_plural': 'Sosial Medialar',
            },
        ),
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='tech_icons/')),
                ('proficiency', models.IntegerField(default=50)),
            ],
            options={
                'verbose_name': 'Texnologiya',
                'verbose_name_plural': 'Texnologiyalar',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField(max_length=300)),
                ('detailed_description', models.TextField()),
                ('image', models.ImageField(upload_to='projects/')),
                ('github_url', models.URLField(blank=True, null=True)),
                ('live_url', models.URLField(blank=True, null=True)),
                ('created_date', models.DateField()),
                ('is_featured', models.BooleanField(default=False)),
                ('technologies', models.ManyToManyField(to='portfolio.techstack')),
            ],
            options={
                'verbose_name': 'Proyekt',
                'verbose_name_plural': 'Proyektlər',
                'ordering': ['-created_date'],
            },
        ),
    ]
